CREATE DATABASE job_recruitment_application ;

CREATE TABLE LOGINF(
	LID CHAR(8) NOT NULL,
	PASS VARCHAR(20)NOT NULL,
	UTYPE VARCHAR(15),
	CONSTRAINT cons1 PRIMARY KEY(LID)
	);

CREATE TABLE APPLICANT(
	APEMAIL VARCHAR(30) NOT NULL,
	APLOCATION VARCHAR(30),
	APFNAME VARCHAR(30) NOT NULL,
	APLNAME VARCHAR(30) NOT NULL,
	LID CHAR(8) NOT NULL,
	CONSTRAINT c2 PRIMARY KEY(APEMAIL),
	CONSTRAINT c3 FOREIGN KEY(LID) REFERENCES LOGINF ON DELETE SET DEFAULT ON UPDATE CASCADE
	);

CREATE TABLE ADMINISTRATOR(
	ADEMAIL VARCHAR(30) NOT NULL,
	ADSSN CHAR(9) NOT NULL,
	ADFNAME VARCHAR(30) NOT NULL,
	ADLNAME VARCHAR(30) NOT NULL,
	LID CHAR(8) NOT NULL,
	CONSTRAINT c4 PRIMARY KEY(ADEMAIL),
	CONSTRAINT c5 UNIQUE(ADSSN),
	CONSTRAINT c6 FOREIGN KEY(LID) REFERENCES LOGINF ON DELETE SET DEFAULT ON UPDATE CASCADE
	);

CREATE TABLE RECRUITER(
	REMAIL VARCHAR(30) NOT NULL,
	RLOCATION VARCHAR(30),
	RNAME VARCHAR(30),
	LID CHAR(8) NOT NULL,
	CONSTRAINT c7 PRIMARY KEY(REMAIL),
	CONSTRAINT c8 FOREIGN KEY(LID) REFERENCES LOGINF ON DELETE SET DEFAULT ON UPDATE CASCADE
	);


CREATE TABLE FEEDBACK(
	FNUMBER INT NOT NULL IDENTITY(1,1),
	APEMAIL VARCHAR(30) NOT NULL,
	COMMENT VARCHAR(350) NOT NULL,
	CONSTRAINT c9 PRIMARY KEY(FNUMBER,APEMAIL),
	CONSTRAINT c10 FOREIGN KEY(APEMAIL) REFERENCES APPLICANT ON DELETE SET DEFAULT ON UPDATE CASCADE
	);

CREATE TABLE FEEDBACK_REVIEWS(
	FNUMBER  INT NOT NULL IDENTITY(1,1),
	APEMAIL VARCHAR(30) NOT NULL,
	ADEMAIL VARCHAR(30) NOT NULL,
	REPLY VARCHAR(350) NOT NULL,
	CONSTRAINT c11 PRIMARY KEY(FNUMBER,APEMAIL,ADEMAIL),
	CONSTRAINT c12 FOREIGN KEY(APEMAIL) REFERENCES APPLICANT ON DELETE SET DEFAULT ON UPDATE CASCADE,
	CONSTRAINT c13 FOREIGN KEY(ADEMAIL) REFERENCES ADMINISTRATOR ON DELETE SET DEFAULT ON UPDATE CASCADE
	);

CREATE TABLE OFFERS(
	JID INT NOT NULL IDENTITY(1,1),
	REMAIL VARCHAR(30) NOT NULL,
	JLOCATION VARCHAR(30),
	JDESCRIPTION VARCHAR(150) NOT NULL,
	is_remote BIT ,
	SALARY INT,
	CONSTRAINT c14 PRIMARY KEY(JID,REMAIL),
	CONSTRAINT c15 FOREIGN KEY(REMAIL) REFERENCES RECRUITER ON DELETE SET DEFAULT ON UPDATE CASCADE
);

CREATE TABLE APPLICATION(
	APEMAIL VARCHAR(30) NOT NULL,
	JID INT NOT NULL ,
	REMAIL VARCHAR(30) NOT NULL,
	CONSTRAINT c16 PRIMARY KEY(APEMAIL,JID,REMAIL),
	CONSTRAINT c17 FOREIGN KEY(JID,REMAIL) REFERENCES OFFERS ON DELETE SET DEFAULT ON UPDATE CASCADE,
	CONSTRAINT c18 FOREIGN KEY(APEMAIL) REFERENCES APPLICANT ON DELETE SET DEFAULT ON UPDATE CASCADE
);